[32m2024-02-29 19:31:57 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB_0 - 41d16cb8-0485-464c-a589-93ce6da2236f - 49235 - LOGS_CAPTURED - Started capturing logs in process (pid: 49235).
[32m2024-02-29 19:31:57 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB_0 - 41d16cb8-0485-464c-a589-93ce6da2236f - 49235 - finnhub_stocks_US - STEP_START - Started execution of step "finnhub_stocks_US".
[32m2024-02-29 19:31:57 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB_0 - 41d16cb8-0485-464c-a589-93ce6da2236f - 49235 - finnhub_stocks_US - STEP_FAILURE - Execution of step "finnhub_stocks_US" failed.

dagster._core.errors.DagsterInvariantViolationError: Cannot access partition_key for a non-partitioned run

Stack Trace:
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 286, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 519, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 201, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 99, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 214, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 183, in _yield_compute_results
    for event in iterate_with_context(
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 467, in iterate_with_context
    next_output = next(iterator)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/workspaces/practical-data-engineering/finnhub-batch-stock-pipeline/finnhub_batch_stock_pipeline/assets/assets.py", line 57, in finnhub_stocks_US
    stock = context.partition_key
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/dagster/_core/execution/context/compute.py", line 1690, in partition_key
    return self.op_execution_context.partition_key
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/dagster/_core/execution/context/compute.py", line 306, in partition_key
    return self._step_execution_context.partition_key
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/dagster/_core/execution/context/system.py", line 391, in partition_key
    raise DagsterInvariantViolationError(
[0m
